### PR TITLE
Big: design improvements, new chat UX, type safety fixes, +misc

### PR DESCRIPTION
**Pull request by padolsey**
Sorry about this very large PR. I found it a bit unavoidable as I had a bunch of intertwined things I wanted to do and atomizing the changes would've added like 50% more time to the process.

@evanhadfield **Happy to pop on a call to chat through the headlines and any questions.**

----

## Rand
- Replace 'OSCCAI' with 'Community Models'

## Type System & Code Quality
- Replaced custom type definitions with Prisma-generated types (removed redundancy)
- Added proper type inference for database queries
- Improved transaction handling with proper typing
- Removed console.log statements and unused imports
- Added a bit of documentation for type usage (needs more tbh!)

## Animation & Performance
- Removed Framer Motion dependency in favor of simpler CSS animations (it was overkill)

## Chat Experience Improvements (/chat + /simple-chat)
- Added chat history persistence via localStorage
- Improved chat UI with better state management
- Added "full-screen" chat experience under `/community-models/chat/*`
- Created new simple-chat variant (useful for less literate users) (we're not yet linking to this tho)
- Added constitution viewer modal for better context 
- Improved chat loading states and transitions

## Mobile & UI Improvements
- Improved mobile responsiveness across the app
- Added mobile hamburger menu with slide-down navigation
- Optimized chat interface for mobile devices
- Added slide-out chat history via FAB button
- Improved constitution modal layout for mobile

## Poll Interface Redesign
- Redesigned poll page layout with white container inline with Tessa's figma
- Added loading skeleton state
- Improved voting interface with better button states
- Added "already voted" indicators (opinionated)
- Improved navigation with Previous/Next buttons (this is an opinionated change - happy to discuss)

## Screenshots

Screenshot 2024-11-20 at 09 13 45

Screenshot 2024-11-20 at 09 14 16
Screenshot 2024-11-20 at 09 14 27
Screenshot 2024-11-20 at 09 14 40
Screenshot 2024-11-20 at 09 15 14
Screenshot 2024-11-20 at 09 15 43
Screenshot 2024-11-20 at 09 16 20
Screenshot 2024-11-20 at 09 16 32
Screenshot 2024-11-20 at 09 16 55

### CODE REVIEW

**Comment by evanhadfield** [comment]
😍 looking so good!

Main thing I notice is some big wonkiness with the Poll.
- If I click through individual view options just a bit too quickly it seems to skip over ones I haven't clicked on
- in Individual view, it looks like I can go to "Previous" and change my vote on (already voted). But then if I vote on all Statements I can no longer access previous and I can't change votes in the list view
- if I do go back to Previous and change my vote, after it skips ahead to the next un-voted-on Statement, if I click Previous again, it goes back and then quickly skips ahead to the un-voted-on Statement again. if I click Previous _again_, it does let me go back.
- in list view of poll, if I click the buttons on a Statement i've already voted on, it starts applying my button click to the next un-voted-on Statement
- even when showing (already voted), the button UI / click reaction suggests that the vote can still be changed, but it appears not to.

Curious about the (already voted) change - seems like you're wanting to prevent changing votes?

**Comment by evanhadfield** [comment]
image

image

Don't want minor UI weirdness to be a blocker to PRs - just noting some spacing weirdness in
1. Contributing a Statement modal
2. Deleting a chat

**Comment by padolsey** [comment]
Thanks for testing!! Shall investigate those bugs. Seems quite a few which concerns me.

> Curious about the (already voted) change - seems like you're wanting to prevent changing votes?

No desire to prevent changing votes. It was more to make it obvious that you'd already voted, since the button 'voted' states are very aesthetically subtle atm.

**Comment by padolsey** [comment]
Ooh yikes yeh I hadn't even tried the 'adding a statement' flow. Thanks for reviewing this stuff deeply!

**Comment by evanhadfield** [comment]
also looks like the local chat history is not saved per-model, and opens in whatever CM chat is opened. Reckon this is undesirable and we'd want the chat saved locally associated with a specific CM (maybe even version?)


image
image
image

**Comment by evanhadfield** [comment]
> Thanks for testing!! Shall investigate those bugs. Seems quite a few which concerns me.
> 
> > Curious about the (already voted) change - seems like you're wanting to prevent changing votes?
> 
> No desire to prevent changing votes. It was more to make it obvious that you'd already voted, since the button 'voted' states are very aesthetically subtle atm.

ah ok! in that case, I think we should take out "(already voted)" and make a more clear UI distinction. Realizing that there's probably a larger conflict here that's fundamentally caused by trying to enable individual-view voting and list-view voting. These are a bit tough to reconcile and maybe we are making things unnecessarily difficult for ourselves to try and develop optimal interfaces for both

**Review by evanhadfield — APPROVED** [review]
Looks good! 🚢

**Pull request merged**
